# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zidXnEFtrEBVAhqIP-xGkyOj2t-zYsPc

Import Dataset
"""

import pandas as pd

df = pd.read_csv("Study Case - Dataset VIX Dummy - Data for Study Case 1.csv")

"""**Purchase Behavior Patterns**

Checkout Rate
"""

checkout_rate = df[df['checkout_date'].notna()].shape[0] / df.shape[0]

"""Conversion Rate"""

conversion_rate = df[df['paid_date'].notna()].shape[0] / df[df['checkout_date'].notna()].shape[0]

"""Repeat Customer Rate"""

repeat_customer_rate = df[df.duplicated(subset='user_id', keep=False)].shape[0] / df.shape[0]

"""Average Order Value"""

average_order_value = df[df['paid_date'].notna()]['paid_date'].count() / df[df['paid_date'].notna()]['user_id'].nunique()

"""Customer Lifetime Value"""

import datetime

# Compute the days between the first purchase date and the last purchase date for each user
df['first_purchase_date'] = pd.to_datetime(df['checkout_date'])
df['last_purchase_date'] = pd.to_datetime(df['paid_date'])
df['customer_lifetime'] = (df['last_purchase_date'] - df['first_purchase_date']).dt.days

# Compute the average customer lifetime value
customer_lifetime_value = df[df['paid_date'].notna()]['customer_lifetime'].mean()

"""**Customer's Location**

Number of Customers by City
"""

customers_by_city = df.groupby('city').size()

"""Customer's Geographic Distribution"""

import matplotlib.pyplot as plt

plt.pie(customers_by_city.values, labels=customers_by_city.index)
plt.show()

"""Lead time

Average Lead Time
"""

df['lead_time'] = (pd.to_datetime(df['paid_date']) - pd.to_datetime(df['checkout_date'])).dt.days
average_lead_time = df[df['paid_date'].notna()]['lead_time'].mean()

"""Median Lead Time"""

median_lead_time = df[df['paid_date'].notna()]['lead_time'].median()